// <auto-generated />
using System;
using Base.Infrastructure.Database.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Base.Infrastructure.Database.EntityFramework.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260724153854_Auth")]
    partial class Auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiresAt");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revokedAt");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "SEC", t =>
                        {
                            t.HasComment("Tokens utilizados para renovar la autenticación.");
                        });
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", "SEC", t =>
                        {
                            t.HasComment("Roles del sistema.");
                        });
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", "SEC", t =>
                        {
                            t.HasComment("Usuarios del sistema.");
                        });
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRole", "SEC", t =>
                        {
                            t.HasComment("Relación entre usuarios y roles.");
                        });
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.TestTableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("InvoiceLinkExtern")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("invoiceLinkExtern");

                    b.Property<int>("InvoiceNumberExtern")
                        .HasColumnType("int")
                        .HasColumnName("invoiceNumberExtern");

                    b.Property<string>("InvoiceRollExtern")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("invoiceRollExtern");

                    b.Property<int>("IziIdExtern")
                        .HasColumnType("int")
                        .HasColumnName("iziIdExtern");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<DateTime>("TimesTamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timesTamp");

                    b.HasKey("Id");

                    b.ToTable("TestTable", "TST");
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.RefreshTokenEntity", b =>
                {
                    b.HasOne("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserRoleEntity", b =>
                {
                    b.HasOne("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.Authentication.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
