// <auto-generated />
using System;
using Base.Infrastructure.Database.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Base.Infrastructure.Database.EntityFramework.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Base.Infrastructure.Database.EntityFramework.Entity.TestTableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdBy");

                    b.Property<string>("InvoiceLinkExtern")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("invoiceLinkExtern");

                    b.Property<int>("InvoiceNumberExtern")
                        .HasColumnType("int")
                        .HasColumnName("invoiceNumberExtern");

                    b.Property<string>("InvoiceRollExtern")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("invoiceRollExtern");

                    b.Property<int>("IziIdExtern")
                        .HasColumnType("int")
                        .HasColumnName("iziIdExtern");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedByAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedByAt");

                    b.Property<DateTime>("TimesTamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timesTamp");

                    b.HasKey("Id");

                    b.ToTable("TestTable", "TST");
                });
#pragma warning restore 612, 618
        }
    }
}
